language: objective-c
compiler:
  - clang

xcode_project: Project/Vision.xcodeproj
xcode_scheme: Debug
xcode_sdk: iphonesimulator7.0

branches:
  only:
    - master

before_install:
  - export LANG=en_US.UTF-8
  - brew update
  - brew upgrade xctool
